### ISSUE TITLE
Direct Input Keybinds

### ISSUE THREAD

**Issue by BinaryEnigma01** [skai2/EDAutopilot#45]
after running the exe, I got the error that everyone seems to get, "Script failed to execute..", after looking at the log and actually running the py script, the reason for my case is:  

> Traceback (most recent call last):
>   File "dev_autopilot.py", line 372, in <module>
>     keys = get_bindings()
>   File "dev_autopilot.py", line 354, in get_bindings
>      binding['key'] = SCANCODE[binding['pre_key']]
> KeyError: 'DIK_HASH'

Before this one, I got the same error but for `DIK_NUMPAD_SUBTRACT`, thought someone just forgot the `NUMPAD_` missing from `directinput.py` and moved along, now I realize that these keybinds aren't very compatible, as HASH (the # character) doesn't seem to even exist in `dinput.h`

It seems that ED can identify these keys in a reliable fashion, but I'm not quite sure how this program could be made to do the same.

After spending a bit of time finding random keys that didn't conflict with anything, it worked (still not on the exe, that one's just broken, although maybe in a similar place).

**Comment by TomW1605** [comment]
there are some known issues with the way we are currently reading in the keybinds file. i think these are fixed in my testing branch, could you please do a fresh clone from [here](https://github.com/TomW1605/EDAutopilot/tree/debug_enabled) let me know if it works. this branch also has some debug windows enabled but these can be ignored.

**Comment by BinaryEnigma01** [comment]
That branch is slightly better (The `]` key works now), but `Key_Hash` is still not available

**Comment by TomW1605** [comment]
hang on what key is the hash key? for me it is shift+3 so there is no actual code for it. what keyboard layout are you using?

**Comment by BinaryEnigma01** [comment]
It's strange, I don't have a hash key either, on my keyboard (pt), it's `~` (Shift and you get `^`), but Elite reads it as `#`, and the key works like normal
The error resulting from it says `KeyError: 'Key_Hash' `

**Comment by TomW1605** [comment]
where is the key physicaly?

**Comment by BinaryEnigma01** [comment]
To the left of RETURN, the `~` and `^` key
![image](https://user-images.githubusercontent.com/21149088/88922805-923b1a00-d268-11ea-86f9-11f9e47a3fd0.png)
In Minecraft, it gets registered as `~`, in Elite Dangerous:
![image](https://user-images.githubusercontent.com/21149088/88923153-286f4000-d269-11ea-8445-2d22ddb91bbf.png)

**Comment by BinaryEnigma01** [comment]
And it's not the keyboard, I've tried 3 now and they all have the exact same behaviour

**Comment by TomW1605** [comment]
ok could you try and see what you get from that key on this site. https://keycode.info/ this is not for scancodes but it is good for seeing how the computer is interpreting the key.

**Comment by BinaryEnigma01** [comment]
![image](https://user-images.githubusercontent.com/21149088/88932359-df71b880-d275-11ea-8500-27103f95b04b.png)

**Comment by TomW1605** [comment]
well now i'm lost. that is the same code as i get from the `/` key. it might be that we simply cannot support this key. without being able to identify the key properly i won't be able to get the code to send to ED.

**Comment by TomW1605** [comment]
i mean worse case we could try just incrementing the code and waiting till ED gets the right key.

**Comment by BinaryEnigma01** [comment]
Brute force is not a good option here, it's better to just inform the user should this error occur

**Comment by TomW1605** [comment]
i don't mean every time i just mean to get the code needed for the future. if i could through something together to try and find the code would you be willing to test it? i don't have a keyboard like that so i wont be able to.

**Comment by BinaryEnigma01** [comment]
Oh, sure
I already looked through `keyboard` module's documentation and the `key_to_scan_codes` function tells me it's 43(decimal), which is apparently `'Key_BackSlash': 0x2B,  # KEY_BACKSLASH`
So the question is: Why does Elite see it as Key_Hash, and why does that not exist?
(The answer that seems most likely right now is: blame FDev and call it a day)

**Comment by TomW1605** [comment]
what does elite do when you try and use back slash?

**Comment by BinaryEnigma01** [comment]
I added it to EDKeyCodes now (And it does work), and I guess I could make the settings menu (Where one can change the start and end keys to the program) always log the keycode for future issues
